"""modification table reception

Revision ID: 35d2b40b48c8
Revises: dc0d61de436a
Create Date: 2022-08-05 01:29:18.263823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35d2b40b48c8'
down_revision = 'dc0d61de436a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reception', 'message_',
               existing_type=mysql.CHAR(length=1),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reception', 'message_',
               existing_type=sa.TEXT(),
               type_=mysql.CHAR(length=1),
               existing_nullable=True)
    # ### end Alembic commands ###
