"""send_file db22.0

Revision ID: 37d0d4dae0f6
Revises: f1b474743146
Create Date: 2022-10-04 15:50:02.959885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37d0d4dae0f6'
down_revision = 'f1b474743146'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_sended', sa.Column('reference', sa.String(length=50), nullable=True))
    op.drop_column('file_sended', 'id_file')
    op.add_column('reception', sa.Column('reference', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reception', 'reference')
    op.add_column('file_sended', sa.Column('id_file', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('file_sended', 'reference')
    # ### end Alembic commands ###
