"""send_file db

Revision ID: f1b474743146
Revises: 35d2b40b48c8
Create Date: 2022-10-04 14:50:29.760133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b474743146'
down_revision = '35d2b40b48c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_sended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_expediteur', sa.Integer(), nullable=True),
    sa.Column('id_destinateur', sa.Integer(), nullable=True),
    sa.Column('id_file', sa.Integer(), nullable=True),
    sa.Column('filetype', sa.String(length=15), nullable=True),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_sended_id'), 'file_sended', ['id'], unique=False)
    op.add_column('reception', sa.Column('file', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reception', 'file')
    op.drop_index(op.f('ix_file_sended_id'), table_name='file_sended')
    op.drop_table('file_sended')
    # ### end Alembic commands ###
